[theme]
primaryColor =  "#00172B" 
backgroundColor = "#FFFFFF"  # Белый фон
secondaryBackgroundColor = "#ddf1ff"  # Пастельный голубой
textColor = "#303030"  # Темно-серый для лучшей читаемости
font = "sans serif"
